services:
  valheim:
    image: ghcr.io/community-valheim-tools/valheim-server
    container_name: valheim-server
    platform: linux/amd64
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
    environment:
      - SERVER_NAME=My Valheim Server
      - WORLD_NAME=Dedicated
      - SERVER_PASS=secret1234 # Must be 5+ characters and NOT contained in the server name
      - SERVER_PUBLIC=true
      - CROSSPLAY=false # Set to true if friends are playing on Xbox or PC Game Pass
    volumes:
      - ./config:/config
      - ./data:/opt/valheim
    restart: unless-stopped
